# Regenerate the forwarding header if the project folder is moved.
$ErrorActionPreference = 'Stop'
$taskConfigPath = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '../parking_client/config.h')).Path.Replace('\', '/')
$taskIncludePath = $taskConfigPath.Replace('"', '\"')
$taskHeader = @"
#pragma once
// Generated by prepare_config.ps1. Reads the original config without copying secrets.
#define DIAGNOSTIC_CONFIG_PATH "$taskIncludePath"
#include "$taskIncludePath"
"@
Set-Content -LiteralPath (Join-Path $PSScriptRoot 'shared_config.h') -Value $taskHeader -Encoding utf8
Write-Output "Shared config: $taskConfigPath"
