#pragma once
// Generated by prepare_config.ps1. Reads the original config without copying secrets.
#define DIAGNOSTIC_CONFIG_PATH "C:/Users/HOANG NAM/Desktop/BAIXE_ARDUINO/esp32/parking_client/config.h"
#include "C:/Users/HOANG NAM/Desktop/BAIXE_ARDUINO/esp32/parking_client/config.h"
